rabbitmq:
    image: rabbitmq
    container_name: sensu-rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=sensu
        - RABBITMQ_DEFAULT_PASS=password
        - RABBITMQ_DEFAULT_VHOST=/sensu
redis:
    image: redis
#uchiwa:
#    image: uchiwa/uchiwa
#    links:
#        - api
#    ports:
#        - 3000:3000
#    volumes:
#        - ./docker/uchiwa:/config
server:
    container_name: sensu-server
    build: docker/server
    links:
        - rabbitmq
        - redis
api:
    container_name: sensu-api
    build: docker/api
    links:
        - rabbitmq
        - redis
#client:
#    container_name: sensu-client
#    build: docker/client
#    links:
#        - rabbitmq
standalone_client:
    container_name: sensu-standalone-client
    build: docker/standalone-client
    links:
        - rabbitmq
grafana:
    image: grafana/grafana
    links:
        - influxdb
    ports:
        - 9094:3000
influxdb:
    image: influxdb
    volumes:
        - ~/junk/influxdb:/var/lib/influxdb
        - ./docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
        - 8083:8083
        - 8086:8086
        - 8089:8089
    command: -config /etc/influxdb/influxdb.conf