rabbitmq:
    image: rabbitmq
    container_name: sensu-rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=sensu
        - RABBITMQ_DEFAULT_PASS=password
        - RABBITMQ_DEFAULT_VHOST=/sensu
redis:
    image: redis
uchiwa:
    image: uchiwa/uchiwa
    links:
        - api
    ports:
        - 3000:3000
    volumes:
        - ./uchiwa:/config
server:
    container_name: sensu-server
    build: server
    links:
        - rabbitmq
        - redis
api:
    container_name: sensu-api
    build: api
    links:
        - rabbitmq
        - redis
client:
    container_name: sensu-client
    build: client
    links:
        - rabbitmq
        - server
